# Generated by Django 4.2.10 on 2025-08-30 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('tgusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Photo')),
                ('education', models.CharField(max_length=255, verbose_name='Education')),
                ('education_level', models.CharField(choices=[('school', 'School (Secondary Education)'), ('college', 'College (Vocational Secondary)'), ('bachelor', 'Bachelor (Incomplete Higher Education)'), ('masters', 'Masters (Higher Education)')], max_length=20, null=True, verbose_name='Education Level')),
                ('profession', models.CharField(max_length=255, null=True, verbose_name='Profession')),
                ('certificate', models.FileField(null=True, upload_to='certificates/', verbose_name='Certificate')),
                ('creative_work', models.TextField(null=True, verbose_name='Creative Work')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Accepted')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.mahalla', verbose_name='Area')),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tgusers.telegramuser', verbose_name='Telegram User')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'db_table': 'submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
